File "C:\Users\bsoo.hwang.SECDS\AppData\Roaming\Blender Foundation\Blender\4.3\scripts\addons\rteach\settings_static.py", line 11, in getter
Traceback (most recent call last):
  File "C:\Users\bsoo.hwang.SECDS\AppData\Roaming\Blender Foundation\Blender\4.3\scripts\addons\rteach\settings_static.py", line 17, in getter
    axis = get_robot_axes()[i]
           ~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range
